/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.alexritian.codegen;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.plugins.JavaBasePlugin;
import org.gradle.api.plugins.JavaPluginExtension;
import org.gradle.api.tasks.SourceSetContainer;
import org.gradle.api.tasks.TaskProvider;
import io.github.alexritian.codegen.containers.PostgresServer;

import static nu.studer.gradle.jooq.util.Gradles.isAtLeastGradleVersion;
import static nu.studer.gradle.jooq.util.Strings.capitalize;

/**
 * @author Too_young
 */
public class CodegenGradlePlugin implements Plugin<Project> {
    public void apply(Project project) {

        // apply Java base plugin, making it possible to also use the jOOQ plugin for Android builds
        project.getPlugins().apply(JavaBasePlugin.class);

        // register build server
        var serverProvider = PostgresServer.getProvider(project);
        // add extension
        var codegenExtension = project.getExtensions().create("jooq", CodegenExtension.class);

        // create configuration for the runtime classpath of the jooq code generator (shared by all jooq configuration domain objects)
        Configuration jooqGeneratorRuntimeConfiguration = createJooqGeneratorRuntimeConfiguration(project, codegenExtension);

        // create a jooq task for each jooq configuration domain object
        codegenExtension.getConfigurations().configureEach(config -> {
            String taskName = "generate" + (config.name.equals("main") ? "" : capitalize(config.name)) + "Jooq";
            TaskProvider<CodeGenerate> jooq = project.getTasks().register(taskName, CodeGenerate.class, codegenExtension.getUseContainer().get(), config,
                    jooqGeneratorRuntimeConfiguration,
                    project.getExtensions());
            jooq.configure(task -> {
                task.getServer().set(serverProvider);
                task.usesService(serverProvider);
                task.setDescription(String.format("Generates the jOOQ sources from the %s jOOQ configuration.", config.name));
                task.setGroup("jOOQ");
            });

            // add the output of the jooq task as a source directory of the source set with the matching name (which adds an implicit task dependency)
            SourceSetContainer sourceSets = getSourceSets(project);
            sourceSets.configureEach(sourceSet -> {
                if (sourceSet.getName().equals(config.name)) {
                    sourceSet.getJava().srcDir(config.getGenerateSchemaSourceOnCompilation().flatMap(b -> b ? jooq.flatMap(CodeGenerate::getOutputDir) : config.getOutputDir()));
                    project.getDependencies().addProvider(sourceSet.getImplementationConfigurationName(),
                            codegenExtension.getEdition().map(e -> e.getGroupId() + ":jooq").flatMap(ga -> codegenExtension.getVersion().map(v -> ga + ":" + v)));
                    project.getDependencies().add(sourceSet.getImplementationConfigurationName(), "org.postgresql:postgresql:42.7.4");
                }
            });
        });
    }

    private SourceSetContainer getSourceSets(Project project) {
        if (isAtLeastGradleVersion("8.0")) {
            return project.getExtensions().getByType(JavaPluginExtension.class).getSourceSets();
        } else {
            return getSourceSetsDeprecated(project);
        }
    }

    @SuppressWarnings("deprecation")
    private SourceSetContainer getSourceSetsDeprecated(Project project) {
        return project.getConvention().getPlugin(org.gradle.api.plugins.JavaPluginConvention.class).getSourceSets();
    }

    /**
     * Adds the configuration that holds the classpath to use for invoking jOOQ. Users can add their JDBC driver and any generator extensions they might have. Explicitly add JAXB
     * dependencies since they have been removed from JDK 9 and higher. Explicitly add Activation dependency since it has been removed from JDK 11 and higher.
     */
    private static Configuration createJooqGeneratorRuntimeConfiguration(Project project, CodegenExtension jooqExtension) {
        Configuration jooqGeneratorRuntime = project.getConfigurations().create("jooqGenerator");
        jooqGeneratorRuntime.setDescription("The classpath used to invoke the jOOQ code generator. Add your JDBC driver, generator extensions, and additional dependencies here.");
        project.getDependencies().addProvider(jooqGeneratorRuntime.getName(),
                jooqExtension.getEdition().map(e -> e.getGroupId() + ":jooq-codegen").flatMap(ga -> jooqExtension.getVersion().map(v -> ga + ":" + v)));
        project.getDependencies().add(jooqGeneratorRuntime.getName(), "io.github.alexritian:codegen-gradle-plugin-runtime:1.0.0");
        return jooqGeneratorRuntime;
    }

}
